from sympy.strategies import condition
import argparse
from src import io
from src.measures import process_all_subjects
from src.eyekit_helper import create_aoi_boxes, seq_from_df
from src.visualization import plot_measure, plot_result_heatmap, plot_correctness
import config

'''----------------------------------------------------------
To use this script, call from the root folder of the repo:
    if 12 subjects (balanced):
        python -m scripts.04_analysis.py --balanced
    if 14 subjects (all):
        python -m scripts.04_analysis.py

Analysis plots are saved in: 
    /plots/analysis/

Analysis results are saved in:
    /data/processed/

Note of usage:
    - files required from previous steps
        - corrected fixations generated by step03
-------------------------------------------------------------'''

def run(balanced=False):                                     
    subject_info = io.load_all_subject_info()           
    subjects = config.BALANCED_COHORT if balanced else io.all_subjects()
    tag      = "balanced_12" if balanced else "all_14"
    response = io.load_response()            

    events_all, aois_all, seqs_all = {}, {}, {}
    for pid in subjects:
        fixations = io.load_checkpoint("fixations_corrected", pid)
        events    = io.load_checkpoint("events", pid)

        aois_all[pid]   = create_aoi_boxes(events, config.RESOLUTION, config.FONT_SIZE)
        seqs_all[pid]   = seq_from_df(fixations, y_col="Y_snapped")
        events_all[pid] = events

    results = process_all_subjects(events_all, seqs_all, aois_all, subject_info, response, config.CONDITION_MAP)
    io.save_output(results, tag,"analysis_results.csv")

    for measure in config.MEASURES:
        if measure in ["initial_fixation_duration","go_past_duration"]:
            plot_measure(results, measure, condition_map=config.CONDITION_MAP, balanced=balanced, show=False, regions=('an', 'spill'),
                                 save_path=io.grand_fig_path(f'{tag}/measure/{measure}'))  
        else:
            plot_measure(results, measure, condition_map=config.CONDITION_MAP, balanced=balanced, show=False,
                     save_path=io.grand_fig_path(f'{tag}/measure/{measure}'))  

        for region in ['rn', 'an', 'spill']:
            plot_result_heatmap(results, measure=measure, region=region, balanced=balanced, show=False, 
                    save_path=io.grand_fig_path(f'{tag}/measure/heatmap_{measure}–{region}'))

    plot_result_heatmap(results, balanced=balanced, show=False, 
                        save_path=io.grand_fig_path(f'{tag}/response/heatmap_confusion'))
    plot_correctness(results, config.CONDITION_MAP,"correctness_an", show=False,
                        save_path=io.grand_fig_path(f'{tag}/response/correctness_an'))
    plot_correctness(results,  config.CONDITION_MAP, "correctness_rn", show=False,
                        save_path=io.grand_fig_path(f'{tag}/response/correctness_rn'))
        


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--balanced", action="store_true")
    run(ap.parse_args().balanced)